### ISSUE TITLE
dotnet 上运行xlua，貌似lua加载比较多的文件会出错

### ISSUE THREAD

**Issue by better666** [Tencent/xLua#880]
我有个配置文件类如下这么多：如果一起加载，就报错。
Configs.ActorConfig()
Configs.BulletConfig()
Configs.EffectConfig()
Configs.PartConfig1()
Configs.BuffConfig()
Configs:DamageConfig()
Configs:DirectionConfig()

Process terminated. A callback was made on a garbage collected delegate of type 'XLuaModel!XLua.LuaDLL.lua_CSFunction::Invoke'.
   at XLua.LuaDLL.Lua.lua_pcall(IntPtr, Int32, Int32, Int32)
   at XLua.LuaDLL.Lua.lua_pcall(IntPtr, Int32, Int32, Int32)
   at XLua.DelegateBridge.Action()
   at LPCFramework.CSCallLua.Initialize()
   at LPCFramework.LuaVMManager.OnInitialize()
   at DiabloBattle.Program.Main(System.String[])

**Comment by chexiongsheng** [comment]
你是不是没加XLUA_GENERAL 宏呢？

**Comment by better666** [comment]
进过大佬提点，除了加XLUA_GENERAL还需要加NET_STANDARD_2_0，才可以在.netcore上跑。
